// Date 06-06-2021

#include <stdio.h>

int main()
{
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    //! gcc -Wall -save-temps tutorial_4.c -o tutorial_4
    int a, b;
    printf("Enter value of number A!\n");
    scanf("%d", &a);
    printf("Enter value of number B!\n");
    scanf("%d", &b);
    printf("The sum of %d and %d is %d! ", a, b, a + b);
    return 0;
}