// Date 08-07-2021

//* You have to fill in values to a template letter.txt
//* Letter.txt looks something like this:
//* Thanks {{name}} for purchasing {{item}} from our outlet {{outlet}}.
//* Please visit our outlet {{outlet}} for any kind of problems. We plan to server you again soon.
//* You have to read this file and replace these values:
//* {{name}}   - Harry
//* {{item}}   - Table Fan
//* {{outlet}} - Ram Laxmi fan outlet

//* Use file functions in c to accomplish the same

#include <stdio.h>
#include <stdlib.h>

int main()
{

    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done
    //* Not Done

    FILE *f = fopen("tutorial_66_exercise_12(letter.txt).txt", "rb");
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);

    char *string = malloc(fsize + 1);
    fread(string, 1, fsize, f);
    fclose(f);

    string[fsize] = 0;

    return 0;
}