// Date 13-06-2021

//* This program asks the user to enter the size of rows and columns of two matrices (a and b). Both of the matrices are 2D array. Your task is to input these 2D arrays from the user, and then your program will display the results. Following is the condition to multiply the two matrices.

//* To multiply two matrices, the number of columns of the first matrix should be equal to the number of rows of the second matrix.

//* When this condition satisfies, your program should return the multiplied matrix result. However, if this condition does not satisfy, then your program should display a message to end-user that it cannot perform the multiplication of matrices.

#include <stdio.h>
#include <stdlib.h>

//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done
//* Not Done

//todo int rows_of_matrix_one;
//todo int columns_of_matrix_one;
//todo int rows_of_matrix_two;
//todo int columns_of_matrix_two;
//todo int *pointer_of_matrix_one;

//todo int matrix_input_taker();
//todo int matrix_final_value_taker();
//todo int matrix_value_printer();

int main()
{
    int m, n, sum = 0;
    int matrix_a[3][4], matrix_b[4][2], output_matrix[3][2];
    printf("First Enter elements of your first matrix\n");
    for (int i = 0; i < 3; i++)
    {
        for (int j = 1; j <= 4; j++)
        {
            printf("Please enter the value of row %d and column %d your matrix \n", i + 1, j + 1);
            scanf("%d", &matrix_a[i][j]);
        }
    }

    printf("Now Enter elements of your second matrix\n");
    for (int i = 0; i < 4; i++)
    {
        for (int j = 1; j <= 2; j++)
        {
            printf("Please enter the value of row %d and column %d your matrix \n", i + 1, j + 1);
            scanf("%d", &matrix_b[i][j]);
        }
    }

    for (int i = 0; i < 3; i++)
    {
        for (int j = 0; j < 2; j++)
        {
            // Calculate the output_matrix
            for (int k = 0; k < 4; k++)
            {
                sum += matrix_a[i][k] * matrix_b[k][j];
            }
            output_matrix[i][j] = sum;
            sum = 0;
        }
    }

    printf("\n\n\n");
    for (int i = 0; i < 3; i++)
    {
        printf("[");
        for (int j = 0; j < 4; j++)
        {
            printf("%5.d,", matrix_a[i][j]);
        }
        printf("]\n");
    }

    return 0;
}
